### ISSUE TITLE
is it working now?

### ISSUE THREAD

**Issue by cordoval** [LoicMahieu/alpine-wkhtmltopdf#3]
ping can we work on this?

how may i help

**Comment by LoicMahieu** [comment]
Hi @cordoval 
Of course you can work on this :)
`wkhtmltopdf` is working on this image but the render is not quite elegant. In my memories, fonts were pixelated.

**Comment by cordoval** [comment]
are you around to pair up?

**Comment by LoicMahieu** [comment]
No. I don't investigate anymore in wkhtmltopdf ;)
My projects still use it but for new one, I will prefer some new solutions like:
- https://github.com/GoogleChrome/puppeteer
- https://github.com/arachnys/athenapdf
....

**Comment by cordoval** [comment]
yeah me neither, i moved to nodejs for that, is faster
