### ISSUE TITLE
wkhtmltopdf (missing)

### ISSUE THREAD

**Issue by Shardj** [LoicMahieu/alpine-wkhtmltopdf#4]
http://dl-3.alpinelinux.org/alpine/edge/testing/

Doesn't look like wkhtmltopdf is in there any more

**Comment by yun548** [comment]
Apparently it's still in the community repository.

I added a working Dockerfile in the PR #5 

I had to add the 2 new libraries to allow **qt5-qtbase-dev** to be installed as apk was marking them as unresolved dependencies.

**Comment by Shardj** [comment]
I'd recommend adding the binary to the repo itself rather than trusting that they'll keep the binary. However I can see the advantage of how it is. Thanks for resolving
